// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgYrFQbTqYRLVPDbBk_sKo9SKi9XjqFQQ',
    appId: '1:659909346406:web:6512c9bad54dc63b0ad9a7',
    messagingSenderId: '659909346406',
    projectId: 'ecommerceapp1122',
    authDomain: 'ecommerceapp1122.firebaseapp.com',
    storageBucket: 'ecommerceapp1122.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFUxL0wsC56WIKI4NCmGz2aSI5LgS4x8',
    appId: '1:659909346406:android:a7da0137ec17b5c50ad9a7',
    messagingSenderId: '659909346406',
    projectId: 'ecommerceapp1122',
    storageBucket: 'ecommerceapp1122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEGUGZHenYeao_4Hd6wRTdw76_CXipEeY',
    appId: '1:659909346406:ios:4e4cbe933d6f703b0ad9a7',
    messagingSenderId: '659909346406',
    projectId: 'ecommerceapp1122',
    storageBucket: 'ecommerceapp1122.appspot.com',
    iosClientId: '659909346406-a3q3h8kfg86t1i2de2jmnris0gaqtbrn.apps.googleusercontent.com',
    iosBundleId: 'com.android.application',
  );
}
